version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: npm install node-sass@4.10.0
      - run: mkdir www
      - run: mkdir www/css/
      - run: ./node_modules/node-sass/bin/node-sass ./scss/toolkit.scss ./www/css/toolkit.css
      - run: ./node_modules/node-sass/bin/node-sass ./scss/scaffolding.scss ./www/css/scaffolding.css
      - run: ./node_modules/node-sass/bin/node-sass ./scss/fonts.scss ./www/css/fonts.css
      - run: cp index.html ./www/index.html
      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - ./  
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "23:3d:99:97:bf:0d:53:70:99:cd:3a:b4:a6:80:e3:81"
      - attach_workspace:
          at: /home/circleci/repo
      - run: |
          set -e
          cd /home/circleci
          chmod -R g+w ./repo/www/
          tar --exclude=repo/.git -czf - repo/ | ssh -o StrictHostKeyChecking=no deploy@chris-shaw.com "
          stream_directory=stream_$CIRCLE_BRANCH
          rm -rf \$stream_directory
          mkdir \$stream_directory
          cd \$stream_directory
          tar -xzf -

          cd ~
          ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH
          "

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
