name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          cp -r src public
      - name: Sass Build
        uses: gha-utilities/sass-build@v0.1.6
        with:
        # Relative path to SASS or SCSS file, eg. _scss/main.scss
          source: test.scss
        # Path compiled CSS should be saved, eg. ~/workspace_sass/assets/css/main.css
          destination: test.css
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
