name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          cp -r src public
      - 
        name: Sass
        uses: gha-utilities/sass-build@v0.1.6
        with:
          source:  scss/toolkit.scss 
          destination: public/toolkit.css
        :  
        
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.1.6
        with:
          source: scss/main.scss
          destination: ./main.css
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
